displayName: AWS Sigv4 Auth
type: middleware
iconPath: .assets/icon.png

import: github.com/LiveOakLabs/traefik_middleware_sigv4

summary: Sign AWS requests - NOTE this is experimental and not ready for production

testData:  # https://min.io/docs/minio/linux/administration/minio-console.html
  service: s3
  endpoint: play.min.io
  region: us-east-1
