version: "3.3"

services:

  traefik:
    image: "traefik:v3.2"
    container_name: "traefik"
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--experimental.localPlugins.${PLUGIN_NAME}.moduleName=${PLUGIN_MODULE}"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./:/plugins-local/src/${PLUGIN_MODULE}

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.routers.whoami.middlewares=whoami-demo"
      - "traefik.http.middlewares.whoami-demo.plugin.${PLUGIN_NAME}.service=lambda"
      - "traefik.http.middlewares.whoami-demo.plugin.${PLUGIN_NAME}.region=us-east-1"
      - "traefik.http.middlewares.whoami-demo.plugin.${PLUGIN_NAME}.endpoint=s6jt2rgliirxvwbhfq7bpbakoe0aigbr.lambda-url.us-east-1.on.aws"
