# This is the zshrc file used in the dev container.
# Edit this file to add aliases or any additional terminal commands.
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="eastwood"

# Add wisely, as too many plugins slow down shell startup.
plugins=(
    git
    terraform
    docker
    vscode
)

source $ZSH/oh-my-zsh.sh